######################################################################
# Automatically generated by qmake (2.01a) Fri Sep 19 09:12:51 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
