sis:
	ensymble py2sis --uid=0xffffffff --appname=Translate --version=0.0.3 \
		--lang=EN --shortcaption=Translate --caption=Translate \
		--caps=LocalServices+NetworkServices+ReadUserData+UserEnvironment+WriteUserData \
		--vendor="Nokia P&P Copenhagen" --icon=translate.svg translate.py
